# For supporting cross-compilation from linux to windows until Odin officially supports it
# mingw doesnt seem to be able to correctly link the .obj files generated by Odin
# Requires https://github.com/mstorsjo/msvc-wine installed at /opt/

odin build . -target:windows_amd64 -build-mode:object
/opt/msvc/bin/x64/link "*.obj" /out:timeout.exe /subsystem:console msvcrt.lib shell32.lib Ws2_32.lib
rm *.obj

